spring.application.name=sistema-inscripciones-api

server.port=8080

spring.datasource.url=jdbc:postgresql://postgres-sistema-contador.postgres.database.azure.com:5432/sistema_inscripciones?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=WILLYvilca#10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

app.frontend.url=https://wonderful-ocean-0e5e2c00f.7.azurestaticapps.net
app.upload-dir=uploads
app.security.admin-token-secret=sistema-inscripciones-admin-local-secret
app.security.admin-token-hours=8
app.reniec.api-url=https://api.decolecta.com
app.reniec.token=${RENIEC_API_TOKEN:sk_17369.XOthrFIm43dv1X63jKVlVDiLiXzGMGUV}
